server:
  port: 8090

spring:
  application:
    name: user-svc

  #Http client
  http:
    serviceclient:
      user:
        base-url: https://dummyjson.com
      payment:
        base-url: https://payment.example.com/v1
      inventory:
        base-url: http://inventory-service:9090

  #Datasource
  datasource:
    url: jdbc:postgresql://localhost:5432/dbproduct
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: never